public with sharing class MyCalculator {
    
    // add
    public static Integer add(Integer a, Integer b) {
        return a + b;
    } 
    
    // subtract
    public static Integer subtract(Integer a, Integer b){
        return a - b;
    }

    // multiply
    public static Integer multiply(Integer a, Integer b){
        return a * b;
    }

    // divide
    public static Decimal divide(Integer a, Integer b){
        return (Decimal) a / b;
    }
    
    
/*   
    public MyCalculator() {

    }
*/
// dd


}